version: '3.8'

services:
  library-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount data directory for CSV/JSON source files
      - ./data:/app/data:ro
      # Mount index directory for SQLite database (persistent)
      - ./index:/app/index
      # Mount source code for hot reload
      - ./api:/app/api
      - ./indexer:/app/indexer
    environment:
      - PYTHONPATH=/app
      - ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  library-ui-dev:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - ./ui/src:/app/src
      - ./ui/public:/app/public
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true  # For file watching in Docker
    depends_on:
      - library-api
    restart: unless-stopped
    stdin_open: true
    tty: true